### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by naderio** [naderio/rerpc#1]
- [X] implement server-side invocation system
- [X] implement server-side express transport
- [X] implement server-side socket.io transport
- [X] enable function to access transport layer
  - `this.transport` => `express` or `socket.io`
  - `this.req`, `this.res`, and `this.next` for Express
  - `this.soc` and `this.ack` for Socket.IO
- [X] enable function context augmentation
  - `rerpc.context = { get user() { return this.req.user; }; ... }` 
- [X] enable payload processing customisation
  - => override `processPayload(payload) `
- [X] enable error processing customisation
  - => override `processError(error) `, `handleErrorOnExpress(error, req, res, next)`, or 
- [X] enable prefix customisation
- [x] implement client
- [x] implement client proxy feature
- [x] implement client-side socket.io transport
- [x] implement client-side http transport
- [X] write tests
- [ ] validate edge cases
- [ ] write more tests
- [ ] add server and client implementations in Python, Ruby, Go, Java, ...
